### YamlMime:ManagedReference
items:
- uid: System.StackOverflowException
  id: StackOverflowException
  children:
  - System.StackOverflowException.#ctor
  - System.StackOverflowException.#ctor(System.String)
  - System.StackOverflowException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: StackOverflowException
  nameWithType: StackOverflowException
  fullName: System.StackOverflowException
  type: Class
  summary: "Wyjątek zgłaszany, gdy stos wykonywania przepełnienia, ponieważ zawiera zbyt wiele wywołań metody zagnieżdżonych. Ta klasa nie może być dziedziczona."
  remarks: "Stackoverflowexception — jest generowany dla wykonywania błędy przepełnienia stosu, zwykle w przypadku rekursji bardzo bezpośrednich lub niepowiązany.       Stackoverflowexception — używa COR_E_STACKOVERFLOW HRESULT, która ma wartość 0x800703E9. <xref:System.Reflection.Emit.OpCodes.Localloc>Stackoverflowexception — zgłasza instrukcji w języku pośrednim (IL).</xref:System.Reflection.Emit.OpCodes.Localloc> Aby uzyskać listę początkowe wartości właściwości dla obiekt stackoverflowexception — zobacz <xref:System.StackOverflowException.%23ctor%2A>konstruktorów.</xref:System.StackOverflowException.%23ctor%2A>      ## Zagadnienia dotyczące wersji w programie .NET Framework 1.0 i 1.1, można przechwycić obiektu stackoverflowexception — (na przykład, aby odzyskać z niepowiązaną rekursję). Począwszy od programu .NET Framework 2.0, nie może przechwycić obiektu o stackoverflowexception — `try` / `catch` bloku, a odpowiedni proces zostanie zakończony domyślnie. W związku z tym należy zapisać swój kod, aby wykrywanie i zapobieganie przepełnienia stosu. Na przykład jeśli aplikacja jest zależna od rekursji, użyj licznik lub warunek stanie Zakończenie pętli cyklicznej. W poniższym przykładzie użyto licznik, aby upewnić się, że liczba cykliczne wywołań `Execute` — metoda nie przekracza maksymalnej zdefiniowane przez stała MAX_RECURSIVE_CALLS.       [!code-vb[System.StackOverflowException.Class#1](~/add/codesnippet/visualbasic/t-system.stackoverflowex_1.vb)][!code-cs[System.StackOverflowException.Class#1](~/add/codesnippet/csharp/t-system.stackoverflowex_1.cs) ]       >  [!NOTE] > stosowanie <xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute>atrybut do metody, która zgłasza stackoverflowexception — nie ma znaczenia.</xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute>   Nadal nie może obsłużyć wyjątku z kodu użytkownika.       Jeśli aplikacja obsługuje środowisko uruchomieniowe języka wspólnego (CLR), można określić, czy CLR powinna wyładować domeny aplikacji, gdzie wyjątek witryny stack overflow występuje i umożliwić kontynuowanie procesu odpowiednie. Aby uzyskać więcej informacji, zobacz [ICLRPolicyManager — interfejs](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public sealed class StackOverflowException : SystemException
  inheritance:
  - System.Exception
  - System.SystemException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.StackOverflowException.#ctor
  id: '#ctor'
  parent: System.StackOverflowException
  langs:
  - csharp
  name: StackOverflowException()
  nameWithType: StackOverflowException.StackOverflowException()
  fullName: System.StackOverflowException.StackOverflowException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.StackOverflowException&quot;> </xref> klasę, <xref:System.Exception.Message*>Właściwości nowe wystąpienie do wiadomości dostarczanych przez system, który opisuje błąd, takie jak &quot;Żądana operacja spowodowała przepełnienie stosu.&quot;</xref:System.Exception.Message*> Ten komunikat bierze pod uwagę bieżące ustawienia kulturowe systemu."
  remarks: "W poniższej tabeli przedstawiono początkowe wartości właściwości dla wystąpienia <xref:System.StackOverflowException>.</xref:System.StackOverflowException>      | Właściwość | Wartość |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| Ciąg z komunikatem o zlokalizowane. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public StackOverflowException ();
    parameters: []
  overload: System.StackOverflowException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.StackOverflowException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.StackOverflowException
  langs:
  - csharp
  name: StackOverflowException(String)
  nameWithType: StackOverflowException.StackOverflowException(String)
  fullName: System.StackOverflowException.StackOverflowException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.StackOverflowException&quot;> </xref> klasy z powodu określonego błędu."
  remarks: "W poniższej tabeli przedstawiono początkowe wartości właściwości dla wystąpienia <xref:System.StackOverflowException>.</xref:System.StackOverflowException>      | Właściwość | Wartość |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Odwołanie o wartości null (`Nothing` w języku Visual Basic). |   | <xref:System.Exception.Message%2A>| Ciąg z komunikatem o. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public StackOverflowException (string message);
    parameters:
    - id: message
      type: System.String
      description: "A <xref:System.String>opisujący błąd.</xref:System.String> Zawartość komunikatu jest przeznaczona do rozumiane przez człowieka. Element wywołujący tego konstruktora jest wymagana, aby upewnić się, że ten ciąg został zlokalizowany dla bieżącego ustawienia kulturowego systemu."
  overload: System.StackOverflowException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.StackOverflowException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.StackOverflowException
  langs:
  - csharp
  name: StackOverflowException(String,Exception)
  nameWithType: StackOverflowException.StackOverflowException(String,Exception)
  fullName: System.StackOverflowException.StackOverflowException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Inicjuje nowe wystąpienie klasy <xref href=&quot;System.StackOverflowException&quot;> </xref> z określonego komunikatu o błędzie i odwołania do wyjątek wewnętrzny będący przyczyną tego wyjątku."
  remarks: "Wyjątek zgłaszany bezpośrednio w wyniku poprzedniego wyjątku może zawierać odwołania do poprzedniego wyjątku we <xref:System.Exception.InnerException%2A>Właściwości.</xref:System.Exception.InnerException%2A> <xref:System.Exception.InnerException%2A>Właściwość zwraca tę samą wartość, która została przekazana do konstruktora lub odwołanie o wartości null (`Nothing` w języku Visual Basic) Jeśli <xref:System.Exception.InnerException%2A>Właściwości nie dostarcza do konstruktora wartości wyjątku wewnętrznego.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       W poniższej tabeli przedstawiono początkowe wartości właściwości dla wystąpienia <xref:System.StackOverflowException>.</xref:System.StackOverflowException>      | Właściwość | Wartość |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Wyjątek wewnętrzny odwołania. |   | <xref:System.Exception.Message%2A>| Ciąg z komunikatem o. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public StackOverflowException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Komunikat o błędzie opisujący przyczynę wyjątek."
    - id: innerException
      type: System.Exception
      description: "Wyjątek będący przyczyną bieżącego wyjątku. Jeśli `innerException` parametr nie jest odwołanie o wartości null (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref> w języku Visual Basic), bieżący wyjątek jest zgłaszany w <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> bloku, który obsługuje wyjątek wewnętrzny."
  overload: System.StackOverflowException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.SystemException
  isExternal: false
  name: System.SystemException
- uid: System.StackOverflowException.#ctor
  parent: System.StackOverflowException
  isExternal: false
  name: StackOverflowException()
  nameWithType: StackOverflowException.StackOverflowException()
  fullName: System.StackOverflowException.StackOverflowException()
- uid: System.StackOverflowException.#ctor(System.String)
  parent: System.StackOverflowException
  isExternal: false
  name: StackOverflowException(String)
  nameWithType: StackOverflowException.StackOverflowException(String)
  fullName: System.StackOverflowException.StackOverflowException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.StackOverflowException.#ctor(System.String,System.Exception)
  parent: System.StackOverflowException
  isExternal: false
  name: StackOverflowException(String,Exception)
  nameWithType: StackOverflowException.StackOverflowException(String,Exception)
  fullName: System.StackOverflowException.StackOverflowException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.StackOverflowException.#ctor*
  parent: System.StackOverflowException
  isExternal: false
  name: StackOverflowException
  nameWithType: StackOverflowException.StackOverflowException
